### ISSUE TITLE
Group Project Ideas

### ISSUE THREAD

**Issue by jung1411** [jung1411/CSCI4100U_Group_Project#1]
Please come up with any group project ideas that meet requirements below:

1.   At least one ListView or GridView widget
2.   At least one meaningful dialog
3.   If using fields like TextField, validate the input
4.   At least 2 screens that you can navigate between
5.   At least a tab bar, app bar or bottom bar on one of the screens
6.   At least one meaningful notification
7.   Storage either local or cloud
8.   An HTTP request
9.   Map or use of Geolocation
10.  If possible, Camera and Change detection

Once ideas are finalized, we can come up with name and we can change the name of the repo as well.

**Comment by nanduu04** [comment]
An application that shows laundromats nearby and their price.  We can use google maps and popups to view the crowd and price.

**Comment by jung1411** [comment]
> An application that shows laundromats nearby and their price. We can use google maps and popups to view the crowd and price.

I think it's a really good idea. Do you have api for it? If so, can you provide it? Thanks!

**Comment by nanduu04** [comment]
> > An application that shows laundromats nearby and their price. We can use google maps and popups to view the crowd and price.
> 
> I think it's a really good idea. Do you have api for it? If so, can you provide it? Thanks!

I'll look into it
